/**
 * Content banks and text generation. Pure module — no DOM access.
 * Every generator accepts an optional `rng` (0..1 function) so tests can
 * seed it for deterministic output; defaults to Math.random.
 */

export const wordBanks = {
  easy: [
    'the',
    'be',
    'to',
    'of',
    'and',
    'a',
    'in',
    'that',
    'have',
    'it',
    'for',
    'not',
    'on',
    'with',
    'he',
    'as',
    'you',
    'do',
    'at',
    'this',
    'but',
    'his',
    'by',
    'from',
    'they',
    'we',
    'say',
    'her',
    'she',
    'or',
    'an',
    'will',
    'my',
    'one',
    'all',
    'would',
    'there',
    'their',
    'what',
    'so',
    'up',
    'out',
    'if',
    'about',
    'who',
    'get',
    'which',
    'go',
    'me',
    'when',
    'make',
    'can',
    'like',
    'time',
    'no',
    'just',
    'him',
    'know',
    'take',
    'people',
    'into',
    'year',
    'your',
    'good',
    'some',
    'could',
    'them',
    'see',
    'other',
    'than',
    'then',
    'now',
    'look',
    'only',
    'come',
    'its',
    'over',
    'think',
    'also',
    'back',
    'after',
    'use',
    'two',
    'how',
    'our',
    'work',
    'first',
    'well',
    'way',
    'even',
    'new',
    'want',
    'because',
    'any',
    'these',
    'give',
    'day',
    'most',
    'us',
    'is',
  ],
  medium: [
    'about',
    'above',
    'across',
    'after',
    'again',
    'against',
    'almost',
    'along',
    'already',
    'also',
    'although',
    'always',
    'among',
    'another',
    'answer',
    'appear',
    'become',
    'before',
    'begin',
    'behind',
    'believe',
    'between',
    'beyond',
    'both',
    'bring',
    'build',
    'business',
    'call',
    'change',
    'child',
    'city',
    'close',
    'company',
    'consider',
    'continue',
    'country',
    'course',
    'develop',
    'different',
    'during',
    'early',
    'enough',
    'every',
    'example',
    'experience',
    'family',
    'follow',
    'general',
    'government',
    'great',
    'group',
    'happen',
    'history',
    'however',
    'important',
    'include',
    'increase',
    'interest',
    'itself',
    'keep',
    'large',
    'later',
    'learn',
    'leave',
    'letter',
    'level',
    'little',
    'local',
    'market',
    'member',
    'might',
    'million',
    'money',
    'month',
    'morning',
    'mother',
    'movement',
    'national',
    'never',
    'number',
    'often',
    'order',
    'others',
    'part',
    'party',
    'perhaps',
    'place',
    'point',
    'policy',
    'possible',
    'power',
    'present',
    'president',
    'problem',
    'program',
    'provide',
    'public',
    'question',
    'rather',
    'really',
    'reason',
    'result',
    'return',
    'right',
    'school',
    'second',
    'service',
    'several',
    'should',
    'since',
    'small',
    'social',
    'something',
    'special',
    'start',
    'state',
    'still',
    'story',
    'student',
    'study',
    'system',
  ],
  hard: [
    'abbreviation',
    'accommodate',
    'achievement',
    'acknowledge',
    'acquisition',
    'administrative',
    'advertisement',
    'ambassador',
    'anaesthesia',
    'anecdotal',
    'anthropologist',
    'architecture',
    'assassination',
    'bibliography',
    'bureaucratic',
    'catastrophe',
    'characteristic',
    'circumstance',
    'classification',
    'collaboration',
    'commemorate',
    'communication',
    'comprehensive',
    'concentration',
    'conceptualize',
    'conscientious',
    'consideration',
    'constitutional',
    'contemporary',
    'controversial',
    'correspondence',
    'demonstration',
    'determination',
    'disappointment',
    'discrimination',
    'distinguish',
    'electromagnetic',
    'embarrassment',
    'encyclopedia',
    'entrepreneur',
    'environmental',
    'establishment',
    'exaggeration',
    'examination',
    'experimental',
    'extraordinary',
    'fascination',
    'fundamental',
    'guaranteed',
    'hallucination',
    'hippopotamus',
    'humanitarian',
    'identification',
    'illustration',
    'implementation',
    'inappropriate',
    'incomprehensible',
    'infrastructure',
    'interpretation',
    'jurisdiction',
    'justification',
    'knowledgeable',
    'manufacturing',
    'mathematical',
    'microscopic',
    'misunderstanding',
    'multiplication',
    'neurological',
    'notwithstanding',
    'observation',
    'opportunity',
    'organization',
    'overwhelming',
    'parliamentary',
    'participation',
    'pharmaceutical',
    'phenomenon',
    'philosophical',
    'photosynthesis',
    'postponement',
    'precipitation',
    'predominantly',
    'preliminary',
    'preoccupation',
    'professional',
    'pronunciation',
    'psychological',
    'questionnaire',
    'reconnaissance',
    'recommendation',
    'refrigerator',
    'rehabilitation',
    'reimbursement',
    'reminiscence',
    'representative',
    'responsibility',
    'revolutionary',
    'sophisticated',
    'specification',
    'straightforward',
    'subsequently',
    'technological',
    'telecommunication',
    'temperament',
    'theoretical',
    'therapeutic',
    'thermometer',
    'tremendous',
    'unconscious',
    'understanding',
    'unemployment',
    'unfortunately',
    'vulnerability',
  ],
};

export const codeSnippets = {
  javascript: [
    'const sum = (a, b) => a + b;',
    'function greet(name) { return `Hello, ${name}!`; }',
    'const arr = [1, 2, 3].map(x => x * 2);',
    'if (user && user.isActive) { sendEmail(user); }',
    'const { name, age } = person;',
    'async function fetchData(url) { const res = await fetch(url); return res.json(); }',
    'const filtered = items.filter(item => item.price > 100);',
    'try { await saveData(payload); } catch (err) { console.error(err); }',
    'export default function App() { return <div>Hello</div>; }',
    'const [count, setCount] = useState(0);',
    'document.addEventListener("click", (e) => { handleClick(e); });',
    'const total = cart.reduce((sum, item) => sum + item.price, 0);',
  ],
  python: [
    'def factorial(n): return 1 if n <= 1 else n * factorial(n - 1)',
    'result = [x ** 2 for x in range(10) if x % 2 == 0]',
    'with open("data.json", "r") as f: data = json.load(f)',
    'class User: def __init__(self, name): self.name = name',
    'import pandas as pd; df = pd.read_csv("data.csv")',
    'if __name__ == "__main__": main()',
    'try: result = risky_operation() except ValueError as e: print(e)',
    'async def fetch_data(url): async with aiohttp.get(url) as resp: return await resp.json()',
    'from typing import List, Optional, Dict',
    'lambda x, y: x + y if x > 0 else y',
  ],
  typescript: [
    'interface User { id: number; name: string; email?: string; }',
    'const greet = (name: string): string => `Hello, ${name}!`;',
    'type Result<T> = { data: T; error: null } | { data: null; error: string };',
    'enum Status { Active = "active", Inactive = "inactive" }',
    'function getUser(id: number): Promise<User> { return fetch(`/api/users/${id}`).then(r => r.json()); }',
    'const config: Record<string, unknown> = {};',
    'export type Props = { children: React.ReactNode; className?: string; };',
    'const [items, setItems] = useState<Item[]>([]);',
  ],
  sql: [
    'SELECT name, email FROM users WHERE active = true ORDER BY created_at DESC;',
    'INSERT INTO orders (user_id, total) VALUES (1, 99.99);',
    "UPDATE products SET price = price * 1.10 WHERE category = 'electronics';",
    'SELECT u.name, COUNT(o.id) as order_count FROM users u LEFT JOIN orders o ON u.id = o.user_id GROUP BY u.name;',
    'CREATE TABLE IF NOT EXISTS logs (id SERIAL PRIMARY KEY, message TEXT, created_at TIMESTAMP DEFAULT NOW());',
    'DELETE FROM sessions WHERE expires_at < NOW();',
    'SELECT DISTINCT category FROM products WHERE price BETWEEN 10 AND 100;',
    'ALTER TABLE users ADD COLUMN last_login TIMESTAMP;',
  ],
};

export const quotes = [
  'The only way to do great work is to love what you do.',
  'Innovation distinguishes between a leader and a follower.',
  'Stay hungry, stay foolish.',
  'The best time to plant a tree was twenty years ago. The second best time is now.',
  'Code is like humor. When you have to explain it, it is bad.',
  'First, solve the problem. Then, write the code.',
  'Simplicity is the soul of efficiency.',
  'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.',
  'Programming is not about typing, it is about thinking.',
  'The most disastrous thing that you can ever learn is your first programming language.',
  'Talk is cheap. Show me the code.',
  'Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.',
  'Make it work, make it right, make it fast.',
  'The function of good software is to make the complex appear to be simple.',
];

function pick(list, rng) {
  return list[Math.floor(rng() * list.length)];
}

/**
 * @param {'easy'|'medium'|'hard'} difficulty
 * @param {() => number} [rng]
 */
export function getRandomWord(difficulty, rng = Math.random) {
  const words = wordBanks[difficulty] || wordBanks.medium;
  return pick(words, rng);
}

/**
 * @param {string} language — falls back to javascript for unknown languages
 * @param {() => number} [rng]
 */
export function getCodeSnippet(language, rng = Math.random) {
  const snippets = codeSnippets[language] || codeSnippets.javascript;
  return pick(snippets, rng);
}

/** @param {() => number} [rng] */
export function getQuote(rng = Math.random) {
  return pick(quotes, rng);
}

/**
 * Route to the right generator for the current settings.
 * @param {{ mode: string, difficulty: string, codeLanguage: string }} settings
 * @param {() => number} [rng]
 */
export function getNextText(settings, rng = Math.random) {
  switch (settings.mode) {
    case 'code':
      return getCodeSnippet(settings.codeLanguage, rng);
    case 'quotes':
      return getQuote(rng);
    default:
      return getRandomWord(settings.difficulty, rng);
  }
}
